### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by vprheli** [107-systems/107-Arduino-CriticalSection#12]
Critical section is not to disable/enable interrupt as i saw in the code sample.

**Comment by aentinger** [comment]
Can't remember asking for your - uninformed - opinion.

**Comment by vprheli** [comment]
In the CritSec-rp2040.cpp are two funcions - 
extern "C" void crit_sec_enter()
{
  noInterrupts();
}
extern "C" void crit_sec_leave()
{
  interrupts();
}
This code disables all interrupts. It is not a critical section as defined. How about if I need a critical section on the timer routine against the main loop and not lose the hardware external interrupt at the same time? This code cannot solve it.

**Comment by aentinger** [comment]
You should go and look into the RP2040 core how exactly `noInterrupts `and `interrupts` are implemented there.

The issue tracker is a not support forum and open-source is provided "as is".
